sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t spglab/wyk7 -f Dockerfile.dev2 .

script:
  - docker run -e CI=true spglab/wyk7 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-test"
  env: "dockertest-env"
  bucket_name: "elasticbeanstalk-us-east-1-087929663130"
  bucket_path: "docker-test"
  edge: true
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
